// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleDbContext.Models;

namespace MultipleDbContext.Data.Migrations.BookRental.BookRentalDB
{
    [DbContext(typeof(BookRentalDbContext))]
    partial class BookRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultipleDbContext.Models.Books.Authors", b =>
                {
                    b.Property<int>("AuthorsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<int>("Religions");

                    b.Property<int>("Sex");

                    b.Property<string>("Username");

                    b.HasKey("AuthorsID");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("MultipleDbContext.Models.Books.Book", b =>
                {
                    b.Property<int>("BooksID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Booksname");

                    b.Property<double?>("Prices");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Title");

                    b.Property<int?>("Username");

                    b.HasKey("BooksID");

                    b.HasIndex("Username");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("MultipleDbContext.Models.Books.Book", b =>
                {
                    b.HasOne("MultipleDbContext.Models.Books.Authors", "Authors")
                        .WithMany()
                        .HasForeignKey("Username");
                });
#pragma warning restore 612, 618
        }
    }
}
